### ISSUE TITLE
Unable to allocate XX GiB for an array with shape (XX, XX) error

### ISSUE THREAD

**Issue by michoug** [ziyewang/MetaBinner#12]
Hi,
I got this error when trying to bin 900k contigs with the coverage of +45 samples

```
Traceback (most recent call last):
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/work/sber/Software/miniconda3/envs/metabinner_env/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 322, in _kmeans_single_elkan
    max_iter=max_iter, verbose=verbose)
  File "sklearn/cluster/_k_means_elkan.pyx", line 236, in sklearn.cluster._k_means_elkan.k_means_elkan
MemoryError: Unable to allocate 3.40 GiB for an array with shape (900786, 506) and data type float64

```

Any ideas on how to resolve that?
Best
Greg

**Comment by ziyewang** [comment]
Hi Greg,

We released a new version (v1.4.3) to support running MetaBinner on larger datasets with lower memory requirements. We mainly changed the parameters while running k-means. You can have a try by running MetaBinner v1.4.3 with "-s huge":

e.g. "bash run_metabinner.sh -a ${contig_file} -o ${output_dir} -d ${coverage_profiles} -k ${kmer_profile} -p ${metabinner_path} -s huge "

Please feel free to let us know if you have further questions. Thanks.

Best,
Ziye

**Comment by michoug** [comment]
Hi Ziye,
Thanks for the help, I tried it and it didn't resolve my issue.
Reducing the number of contigs by removing those smaller than 2kb did so
Best
Greg

**Comment by ziyewang** [comment]
Thanks very much for your feedback.

Best,
Ziye
